name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      ref:
        description: ref
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Tools
        uses: liblaf/actions/install@main
        with:
          brew: coreutils make
          choco: gnuwin32-coreutils.install make
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: wildmeshing/TriWild
          ref: ${{ inputs.ref }}
      - name: Create Build Directory
        run: mkdir --parents --verbose "./build/"
      - name: Configure
        run: cmake .. -D CMAKE_BUILD_TYPE=Release
        working-directory: ./build/
      - name: Build
        run: make --jobs
        working-directory: ./build/
      - name: Rename
        run: |-
          install -D --mode="u=rwx,go=rx" --verbose "./build/TriWild" "./dist/TriWild-${{ runner.arch }}-${{ runner.os }}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ runner.arch }}-${{ runner.os }}
          path: ./dist/
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # TODO: fix windows build
          # - windows-latest
      fail-fast: false

  test:
    name: Test
    needs:
      - build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Tools
        uses: liblaf/actions/install@main
        with:
          brew: coreutils
          choco: gnuwin32-coreutils.install
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ runner.arch }}-${{ runner.os }}
          path: ./dist/
      - name: Prepare
        run: |-
          install --mode="u=rwx,go=rx" --verbose "./dist/TriWild-${{ runner.arch }}-${{ runner.os }}" "./dist/TriWild"
          mkdir --parents --verbose "./outputs/"
      - name: Clone Data
        uses: actions/checkout@v4
        with:
          repository: wildmeshing/data
          path: ./data/
      - name: Help
        run: ./dist/TriWild --help
      - name: Test
        run: |-
          ./dist/TriWild --input "./data/rocket.obj" --output "./outputs/rocket.msh"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ runner.arch }}-${{ runner.os }}
          path: ./outputs/
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
      fail-fast: false

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-release
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: dist-*
          merge-multiple: true
      - name: Release
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: ./dist/*
          tag: dev
